const ACTIONS = {
	EDIT_ABOUT: "EDIT_ABOUT",
	GET_USER: "GET_USER",
	LOG_OUT: "LOG_OUT",
	ADD_WEEK: "ADD_WEEK",
	DECREMENT_WEEK: "DECREMENT_WEEK",
	GET_USER_BY_TOKEN: "GET_USER_BY_TOKEN",
};

export default ACTIONS;
